using System.Text.Json.Serialization;
using McpToolkit.JsonRpc;

namespace McpToolkit;

[JsonSourceGenerationOptions(
    GenerationMode = JsonSourceGenerationMode.Default,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(JsonRpcMessage))]
[JsonSerializable(typeof(JsonRpcRequest))]
[JsonSerializable(typeof(JsonRpcResponse))]
[JsonSerializable(typeof(JsonRpcNotification))]
[JsonSerializable(typeof(JsonRpcError))]
[JsonSerializable(typeof(Annotations))]
[JsonSerializable(typeof(ToolAnnotations))]
[JsonSerializable(typeof(CancelledNotificationParams))]
[JsonSerializable(typeof(ClientCapabilities))]
[JsonSerializable(typeof(ClientCapabilitiesRoots))]
[JsonSerializable(typeof(CompleteRequestParams))]
[JsonSerializable(typeof(CompleteResult))]
[JsonSerializable(typeof(CompleteArgument))]
[JsonSerializable(typeof(Reference))]
[JsonSerializable(typeof(Completion))]
[JsonSerializable(typeof(Content))]
[JsonSerializable(typeof(EmptyResult))]
[JsonSerializable(typeof(InitializeRequestParams))]
[JsonSerializable(typeof(InitializeResult))]
[JsonSerializable(typeof(InitializedNotificationParams))]
[JsonSerializable(typeof(Implementation))]
[JsonSerializable(typeof(NotificationParams))]
[JsonSerializable(typeof(SetLevelRequestParams))]
[JsonSerializable(typeof(LoggingMessageNotificationParams))]
[JsonSerializable(typeof(PaginatedRequestParams))]
[JsonSerializable(typeof(PaginatedResult))]
[JsonSerializable(typeof(ProgressNotificationParams))]
[JsonSerializable(typeof(ProgressToken))]
[JsonSerializable(typeof(Prompt))]
[JsonSerializable(typeof(PromptArgument))]
[JsonSerializable(typeof(PromptMessage))]
[JsonSerializable(typeof(GetPromptRequestParams))]
[JsonSerializable(typeof(GetPromptResult))]
[JsonSerializable(typeof(ListPromptsRequestParams))]
[JsonSerializable(typeof(ListPromptsResult))]
[JsonSerializable(typeof(PromptListChangedNotificationParams))]
[JsonSerializable(typeof(RequestParams))]
[JsonSerializable(typeof(RequestParamsMetadata))]
[JsonSerializable(typeof(ResourceContents))]
[JsonSerializable(typeof(Resource))]
[JsonSerializable(typeof(ReadResourceRequestParams))]
[JsonSerializable(typeof(ReadResourceResult))]
[JsonSerializable(typeof(ListResourcesRequestParams))]
[JsonSerializable(typeof(ListResourcesResult))]
[JsonSerializable(typeof(ResourceUpdatedNotificationParams))]
[JsonSerializable(typeof(ResourceTemplate))]
[JsonSerializable(typeof(ListResourceTemplatesRequestParams))]
[JsonSerializable(typeof(ListResourceTemplatesResult))]
[JsonSerializable(typeof(Root))]
[JsonSerializable(typeof(ListRootsRequestParams))]
[JsonSerializable(typeof(ListRootsResult))]
[JsonSerializable(typeof(RootsListChangedNotificationParams))]
[JsonSerializable(typeof(CreateMessageRequestParams))]
[JsonSerializable(typeof(CreateMessageResult))]
[JsonSerializable(typeof(SamplingMessage))]
[JsonSerializable(typeof(ModelPreferences))]
[JsonSerializable(typeof(ModelHint))]
[JsonSerializable(typeof(ServerCapabilities))]
[JsonSerializable(typeof(ServerPromptsCapabilities))]
[JsonSerializable(typeof(ServerResourcesCapabilities))]
[JsonSerializable(typeof(ServerToolsCapabilities))]
[JsonSerializable(typeof(Tool))]
[JsonSerializable(typeof(CallToolRequestParams))]
[JsonSerializable(typeof(CallToolResult))]
[JsonSerializable(typeof(ListToolsRequestParams))]
[JsonSerializable(typeof(ListToolsResult))]
[JsonSerializable(typeof(ToolListChangedNotificationParams))]
public partial class McpJsonSerializerContext : JsonSerializerContext
{
}